//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ShMoveitService
{
    public class SHMoveitServiceRequest : Message
    {
        public const string RosMessageName = "sh_moveit_service/SHMoveitService";

        public int phase;

        public SHMoveitServiceRequest()
        {
            this.phase = 0;
        }

        public SHMoveitServiceRequest(int phase)
        {
            this.phase = phase;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.phase));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.phase = BitConverter.ToInt32(data, offset);
            offset += 4;

            return offset;
        }

        public override string ToString()
        {
            return "SHMoveitServiceRequest: " +
            "\nphase: " + phase.ToString();
        }
    }
}
