//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hoap3MoveitService
{
    public class HOAP3MoverServiceResponse : Message
    {
        public const string RosMessageName = "hoap3_moveit_service/HOAP3MoverService";

        public Moveit.RobotTrajectory[] trajectories;

        public HOAP3MoverServiceResponse()
        {
            this.trajectories = new Moveit.RobotTrajectory[0];
        }

        public HOAP3MoverServiceResponse(Moveit.RobotTrajectory[] trajectories)
        {
            this.trajectories = trajectories;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(trajectories.Length));
            foreach(var entry in trajectories)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var trajectoriesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.trajectories= new Moveit.RobotTrajectory[trajectoriesArrayLength];
            for(var i = 0; i < trajectoriesArrayLength; i++)
            {
                this.trajectories[i] = new Moveit.RobotTrajectory();
                offset = this.trajectories[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "HOAP3MoverServiceResponse: " +
            "\ntrajectories: " + System.String.Join(", ", trajectories.ToList());
        }
    }
}
