//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Hoap3MoveitService
{
    public class HOAP3MoverServiceRequest : Message
    {
        public const string RosMessageName = "hoap3_moveit_service/HOAP3MoverService";

        public int phase;
        public Geometry.Pose pose;

        public HOAP3MoverServiceRequest()
        {
            this.phase = 0;
            this.pose = new Geometry.Pose();
        }

        public HOAP3MoverServiceRequest(int phase, Geometry.Pose pose)
        {
            this.phase = phase;
            this.pose = pose;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(BitConverter.GetBytes(this.phase));
            listOfSerializations.AddRange(pose.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            this.phase = BitConverter.ToInt32(data, offset);
            offset += 4;
            offset = this.pose.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "HOAP3MoverServiceRequest: " +
            "\nphase: " + phase.ToString() +
            "\npose: " + pose.ToString();
        }
    }
}
